apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: demo-ops
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis-deployment
  labels:
    app: redis
  namespace: demo-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.0.5-alpine3.12
        name: redis
        command: ["redis-server"]
        args: ["--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /data
          type: DirectoryOrCreate
      restartPolicy: Always